src/components/WalletTabs.vue
src/pages/wallet/Activity.vue
src/plugins/Topup/moonpay.ts
src/utils/topup.ts

Followups for all the tester feedback on 15.2.22 testing sheet.
- On activity screen filter option is not visible on "android chrome"
- USDC(SOL) option added in moonpay

feat: added fixes for test findings

---

package.json
src/modules/controllers.ts

feat: localstorage

---

src/plugins/i18nPlugin.ts

fix: added fixes for cannot load unknown.json

---

src/components/transfer/TransferTokenSelect.vue

- Disabled color swap animation on transfer page.

feat: disabled hover colour change on transfer selector

---

src/modules/controllers.ts

faster logout.
wait openlogin logout before proceed
Bug on case openlogin logout error. 
- redirect to main without clear state  
- openlogin logout as non blocking
- remove redirect to `'/'`
-

fix: change openlogin.logout to non blocking

---

src/pages/Frame.vue
src/utils/helpers.ts

- [x ] Feature
Issue Number: SOL-159

SOL-159 : Add a way to make a list of all dapps using adapter.

---

src/components/common/Toast.vue
src/main.ts
src/sentry.ts
src/utils/ErrorHandler.ts

SOL-156 : Gracefully handle the RPC down error

---

src/components/WalletTabs.vue

- Added position fixed to mobile bottom tabs navbar.

fix: mobile navbar always visible

---

tests/auth-helper.ts
tests/e2e/activity/activity.test.ts
tests/e2e/home/home.test.ts
tests/e2e/settings/settings.test.ts
tests/e2e/transfer/transfer.test.ts

- Updated e2e test auth helpers.

fix: E2E tests updated auth-helper to support new login flow

---

src/components/WalletTabs.vue
src/pages/wallet/Nft.vue
tailwind.config.js

1. Content hidden behind mob nav bar

UI FIX 1 : Mob nav bar issue

---

src/components/common/TextField.vue
src/components/payments/PaymentConfirm.vue
src/components/permissions/Permissions.vue
src/components/permissionsTx/PermissionsTx.vue
src/components/settings/AddressBook.vue
src/components/transfer/TransferConfirm.vue
src/components/transfer/TransferNFT.vue
src/components/transfer/TransferSPL.vue
src/main.css
src/pages/ConfirmNft.vue
src/pages/ConfirmSpl.vue
src/pages/wallet/Activity.vue

- Fixed text-input width when no child element is present.
- Made dialog headings non focusable to remove outline.
- Set default outline color to white (to fix yellow outline on mobile)
- Standardized all popup colours + bg colours.
- Other misc fixes (padding, margin etc)

fix: ui fixes

---

tests/auth-helper.ts
tests/e2e/transfer/transfer.test.ts
tests/transfer.utils.ts

-  Bugfix
-  Refactoring (no functional changes, no api changes)
-  broken test for NFT transfer
- usage of controller state
- fixed NFT transfer test
- removed controller state 
- refactoring

fixed broken transfer tests, removed controller state usage

---

src/pages/Frame.vue

support embed network enum
only support providerConfig for embed
- support embed network enum
-
-

feat: support embed network

---

src/components/WalletTabs.vue
src/components/activity/ActivityItem.vue

- Text aligned to left in transaction activity item.

fix: text aligned to left in tx item

---

src/components/settings/AccountDetails.vue
src/controllers/TorusController.ts
src/modules/controllers.ts
src/pages/Frame.vue
src/pages/wallet/Transfer.vue

fix: openWalletPopup
missing changes from PR https://github.com/torusresearch/solana-wallet/pull/190
selectedAddress need to be clear upon trigger login to avoid show wallet during login
show wallet during login in progress
- hide wallet during login
-
-

fix: add hasSelectedPrivateKey

---

src/components/WalletTabs.vue
src/modules/controllers.ts
src/pages/Logout.vue
src/pages/wallet/Nft.vue
src/utils/helpers.ts

- Added broadcast channel logout to provider.request() logout message.
- Refactoring

fix: logout broadcast channel

---

src/components/TokenBalance.vue
src/pages/wallet/Transfer.vue

- Fixed width of token selector, token balance.
- Added token balance on nfts.

fix: transfer page ui component widths

---

src/modules/controllers.ts
src/utils/const.ts

fix: changed to genesysgo mainnet, removed old network state from logout

---

package.json
src/config.ts
src/utils/helpers.ts

feat: new table

---

src/controllers/TorusController.ts
src/modules/controllers.ts
src/router.ts
src/utils/const.ts

save state on privatekey login
update mainnet rpc url
-
-
-

fix: saveState on private key login

---

src/controllers/TorusController.ts

use generated tempKey public key as state's index key
this is to support multiple device backend restore  
using derived public key as index key
- use random generated tempKey's public key as index key
-
-

feat: use temp's public key as index key

---

src/pages/Frame.vue

Fix restore from backend for embed login
Embed not able to restore from backend
- restore from backend for embed login
-
-

fix: restoreFrombackend

---

src/pages/wallet/Transfer.vue

[HOTFIX]: SPL TRANSFER

---

tests/e2e/topup/topup.test.ts
tests/topup.utils.ts

-  Bugfix
- broken top up test
- fixed broken top up tests

fix: broken top up e2e tests

---

src/controllers/TorusController.ts

Fix sentry issue for develop
PR https://github.com/torusresearch/solana-wallet/pull/230
- fix sentry issue
-
-

fix: sentry issue

---

src/controllers/TorusController.ts

Reset preference state on login
restored preference state prevented fresh login
- reset preference state on login
-
-

fix: reset preference state on login

---

src/controllers/TorusController.ts

Record Login for Fast Login from embed
Do not record Login for fast Login from Embed
- Record Login for Fast Login from Embed
-
-

feat: record fastLogin

---

src/components/WalletBalance.vue
tests/e2e/transfer/transfer.test.ts

Tracking the NFT transfer test here : https://toruslabs.atlassian.net/browse/SOL-191

[E2E TESTS] : currency change test failing

---

tests/auth-helper.ts

Fix e2e tests which are broken due to update of key restoration
All e2e test fail
- All e2e test passed except nft transfer which check for a particular nft (which might have been transferred out from testing account)
-
-

fix: e2e test broken due to restore flow

---

src/controllers/TorusController.ts

fix spl transfer for new token account
spl transfer to new account is broken due to the address owner is incorrectly set
- spl transfer to new account with address owner set correctly
-
-

fix: Master - transfer spl 

---

src/controllers/TorusController.ts

fix spl transfer for new token account
spl transfer to new account is broken due to the address owner is incorrectly set
- spl transfer to new account with address owner set correctly
-
-

fix: transfer spl

---

src/components/discover/DappItem.vue
src/controllers/TorusController.ts
src/modules/controllers.ts

Return instance id

---

src/utils/const.ts

use google rpc for master
-
-
-

fix: use google rpc for master

---

src/components/discover/DappItem.vue
src/pages/wallet/Discover.vue

redirect on `url` search params is provided during embed wallet popup
na
redirect on `url` searchparams provided for embed wallet popup
-
-
-

fix: redirect on url's param provided

---

src/router.ts

fast redirection from discover page need to await for key restoration to be completed
- await for key restoration before redirect
-
-

fix: await for fast redirection from discover page

---

src/components/permissions/Permissions.vue

fix message display format
Message format is not correctly display
-
-
-

fix: fix siw message display format

---

src/utils/const.ts

api.google.mainet-beta.solana.com having ssl cert issue
change to ssc-dao for now
-
-
-

fix: mainet rpc develop

---

src/utils/const.ts

api.google.mainet-beta.solana.com having ssl cert issue 
change to ssc-dao for now
-
-
-

fix: mainnet-rpc

---

package.json

fix: bump open login

---

src/utils/const.ts

update rpc with quiknode rpc
- update rpc with quiknode rpc
-
-

fix: update with quiknode rpc

---

src/controllers/TorusController.ts

log warn for decrypt error
log error for restoring error
log error whenever there is issue during restoring (include fetching and decrypt data)
log warning for fetching and decrypting
log error for restoring state flow
-
-
-

feat: log warn for decrypt error

---

src/controllers/TorusController.ts
src/pages/Frame.vue
src/utils/enums.ts

replace google rpc node saved in local storage
-
-
-

fix: replace google rpc saved in localstorage

---

src/controllers/TorusController.ts
src/modules/controllers.ts

- save ephemeral in sessionStorage
- 
safari and brave is not able to restore on popup
- safari and brave able to restore on popup
- safari and brave works on the key injection
-

fix: safari and brave issue

---

src/components/nav/AccountMenuList.vue
src/controllers/TorusController.ts
src/pages/End.vue
src/utils/enums.ts

Session management in wallet
User can change account after login in the wallet
-
-
-

feat: session mgnt in wallet

---

package.json
src/pages/End.vue
src/pages/Login.vue
src/pages/RedirectFlowHandler.vue
src/pages/RedirectHandler.vue
src/pages/Start.vue
tailwind.config.js

Use spinning loader instead of `T` loader
-
-
-

fix: t loader to spinning loader

---

src/controllers/TorusController.ts

fix: fractal hotfix

---

src/pages/wallet/Activity.vue
src/pages/wallet/NftDetail.vue

- add loading indicator for nft collection
- add text when no activity found

Add UI elements for better visibility

---

package-lock.json
package.json
src/components/home/ImportToken.vue
src/components/home/SplCard.vue
src/components/payments/EstimateChanges.vue
src/components/transfer/TransferConfirm.vue
src/components/transfer/token-helper.ts
src/controllers/TorusController.ts
src/directives/google-analytics.ts
src/modules/controllers.ts
src/pages/ConfirmNft.vue
src/pages/ConfirmSpl.vue
src/pages/wallet/Activity.vue
src/pages/wallet/Home.vue
src/pages/wallet/NftDetail.vue
src/pages/wallet/Transfer.vue
src/utils/bonfida.ts
src/utils/enums.ts
src/utils/helpers.ts
src/utils/interfaces.ts
tests/controller/mockConnection.ts

Initial implementation estimate transaction with spl2.0
-
-
-

feat: inital estimation transaction with spl2.0

---

package-lock.json
package.json
src/controllers/TorusController.ts
src/modules/controllers.ts
src/pages/wallet/Nft.vue

fix: remove unwanted metaplex dependancies

---

src/utils/instruction_decoder.ts

update parse spa token instruction with spl lib 2.0
parse createAssociateAccount
-
-
-

fix: update parse spl inst

---

package.json
public/index.html
src/pages/Login.vue

improved the lighthouse performance for login page

fix: changes to improve performance

---

src/pages/wallet/Transfer.vue

- fix address input flickering

fix: address flickering for sol domain

---

src/components/payments/PaymentConfirm.vue
src/pages/Confirm.vue
src/pages/ProviderChange.vue
src/pages/RedirectHandler.vue
src/pages/redirectflow/ProviderChange.vue

brave browser using broadcastchannel-server to communicate with embed popup causing delay in loading and closing popup.
Adding loading ui in the delay during loading or closing (after approve/reject)
-
-
-

feat: popup loading ui

---

src/components/FullDivLoader.vue
src/components/transfer/TransferNFT.vue
src/components/transfer/TransferSPL.vue
src/pages/404.vue
src/pages/RedirectFlowHandler.vue
src/pages/redirectflow/Confirm.vue
src/pages/redirectflow/ConfirmMessage.vue
src/pages/redirectflow/ConfirmNft.vue
src/pages/redirectflow/ConfirmSpl.vue
src/pages/redirectflow/ProviderChange.vue
src/router.ts
src/utils/redirectflow_helpers.ts
test-redirect-flow/index.html

same feat as #339 but for redirectflow
Clean up some redirectflow logic
-
-
-

Feat/redirecflow loading UI

---

src/pages/Frame.vue
src/utils/helpers.ts

hide crisp when frame is not full screen
-
-
-

fix: always hide crisp when frame not fullscreen

---

src/pages/Confirm.vue

some dapp is using signAllTransaction even for only 1 Transaction.
detect this scenario to estimate balance changes with simulateTransaction
-
-
-

fix: detect signAllTransaction with 1 Transaction

---

src/components/frame/PopupLogin.vue
src/controllers/TorusController.ts
src/pages/Frame.vue
src/sentry.ts

fix sentry
hotfix iframe crisp
-
-
-

fix: fix sentry

---

src/controllers/TorusController.ts

Fix CRISP
add await so that restore is completed before responding to embed login which might cause issue to CRISP due to reactivity
-
-
-

fix: crisp

---

package-lock.json
package.json
src/controllers/TorusController.ts
src/modules/controllers.ts

This PR is needed for the controller https://github.com/torusresearch/controllers/pull/159
-
-
-

fix: nfts unknown

---

src/router.ts

fix: on click of send nft in embed wallet the dropdown is having solana as selected option 
expected: it should be of the nft we clicked

fix: transfer nft dropdown issue

---

tests/setup.js
tsconfig.json

Fix mocha ts-node importing sag files
-
-
-

fix: mocha ts-node import svg

---

src/components/payments/SolanaPay.vue
src/pages/wallet/Pay.vue

fix flickering
add message modal on transfer
redirect to home on cancel/error
-
-
-

fix: solanapay

---

src/pages/End.vue

update end page's account management's css
-
-
-

fix: endpage css for mobile

---

package.json
src/components/payments/PaymentConfirm.vue
src/components/payments/SolanaPay.vue
src/pages/wallet/Transfer.vue
src/utils/solanaHelpers.ts

upgrade Solana Pay to 0.2.1
-
-
-

feat: upgrade solanapay to 0.2.1

---

src/components/settings/AddressBook.vue
src/pages/wallet/Transfer.vue
src/utils/solanaHelpers.ts

fix: transfer dropdown issue

---

src/components/WalletTabs.vue
src/components/settings/Language.vue
src/components/settings/index.ts
src/directives/google-analytics.ts
src/pages/wallet/Nft.vue
src/pages/wallet/Settings.vue
src/utils/enums.ts

feat: move language from navbar to setting

---

src/components/WalletTabs.vue
src/components/topup/gateways/BaseTopup.vue
src/controllers/TorusController.ts
src/directives/google-analytics.ts
src/pages/redirectflow/Confirm.vue

Fix wallet tab header item position
-
-
-

fix: wallet tab header

---

src/controllers/TorusController.ts
src/pages/End.vue
src/pages/Start.vue

Skip endpage on domain check
fix: openlogin sdk update- relogin deprecated
-
-
-

feat: skip endpage on domain check

---

src/utils/helpers.ts

fix: mask crisp .is error

---

src/components/common/CheckBox.vue
src/components/common/ComboBox.vue
src/pages/wallet/Transfer.vue

feat: add contact while transfer

---

src/components/home/QrcodeDisplay.vue
src/modules/controllers.ts

fixes for issues :
* While opening Solana QR code image there is a weird layout shift happening 
* Tokens with no ui amount are showing up(I.e if I. Transfer all belonging of a token still shows up in home page with zero token value)

fix: home page issues

---

src/pages/wallet/NftDetail.vue
src/utils/interfaces.ts

feat: fetch popular NFT to display in NFT page in case of no token being held by the user

feat: popualr NFT

---

.github/workflows/pr.yml

NFT page fixes

---

src/controllers/TorusController.ts

fix: restore previous selected addres

---

src/pages/Start.vue

extend in conjunction of using idToken as Solana-backend auth
PR 
https://github.com/torusresearch/solana-backend/pull/63
https://github.com/torusresearch/controllers/pull/175
-
-
-

feat: extend idToken expiry to 3days

---

package-lock.json
package.json
src/controllers/TorusController.ts
src/modules/controllers.ts
src/utils/bonfida.ts
tests/controller/controllerModule.test.ts

update bonfida name resolve
-
-
-

feat: add bonfida

---

src/plugins/Topup/moonpay.ts

haven't tested the entire flow to purchase usd!!

feat: support usdc sol topup

---

src/components/settings/Network.vue
src/utils/const.ts

cherry pick network error hotfix commit from master 
-
-
-

fix: cherry pick network error hotfix commit from master

---

src/utils/const.ts

Replacing quicknode api key with a new key. 
-
-
-

feat: update quiknodeKey

---

src/components/payments/SolanaPay.vue
src/utils/solanaHelpers.ts

solana pay unable to process uriencoded component
This pr fix the uriencoded component decoding
-
-
-

fix: solana pay request link

---

src/utils/const.ts

New endpoint

---

src/utils/const.ts

fix: update rpc endpoints

---

src/modules/controllers.ts

refresh after logout will have unhandled error
the error is handle by catch 
-
-
-

fix: logout issue

---

src/modules/controllers.ts
tests/controller/controllerModule.test.ts

fix: rt to t

---

src/plugins/i18nPlugin.ts

fix: en not loaded when browser lang is set

---

package-lock.json
package.json

fix: update package

---

package-lock.json
package.json
src/App.vue
src/auth/OpenLogin.ts
src/auth/OpenLoginHandler.ts
src/components/home/SplCard.vue
src/controllers/TorusController.ts
src/modules/auth.ts
src/modules/controllers.ts
src/pages/End.vue
src/pages/Frame.vue
src/pages/Login.vue
src/router.ts
src/utils/helpers.ts
src/utils/redirectflowHelpers.ts
tests/controller/controllerModule.test.ts

Fix rehydration using openlogin v6
fix error on unavailable currency rate
-
-
-

fix: rehydration

---

src/components/transfer/token-helper.ts
src/controllers/TorusController.ts
src/modules/controllers.ts

feat: custom token

---

src/components/home/ImportTokenConfirmation.vue
src/pages/wallet/Home.vue

feat: import token confirmation popup for spl tokens

---

src/components/home/ImportToken.vue
src/components/home/ImportTokenConfirmation.vue
src/pages/wallet/Home.vue

fix: import token

---

src/components/home/ImportTokenConfirmation.vue
src/components/home/SplCard.vue
src/components/topup/gateways/BaseTopup.vue
src/components/transfer/token-helper.ts
src/controllers/TorusController.ts
src/utils/interfaces.ts

fix: refresh token and import tag

---

src/pages/wallet/Transfer.vue

update error with insufficient sol for account that is not debited before when user try to do transactions
-
-
-

fix: insufficient sol

---

.vscode/settings.json
src/modules/controllers.ts
src/pages/Confirm.vue
src/pages/ConfirmMessage.vue
src/pages/End.vue
src/pages/ProviderChange.vue

don't use bc server option
Uses server option for broadcast channel all the time
- Don't use server option of broadcast channel

don't use bc server option

---

package-lock.json
package.json
src/controllers/PrefrenceController.ts
src/controllers/TorusController.ts
src/utils/instructionDecoder.ts
src/utils/solanaHelpers.ts
src/utils/tkey/storageLayer.ts

add priority fee for spl transfer
-
-
-

fix: add priority fee for spl transfer
